# backend-svc-lb.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend-lb
  namespace: gangwon
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - port: 80              # 바깥에서 보는 포트
      targetPort: 8880      # Pod 안 컨테이너 포트
